spring.application.name=PotatoChip

spring.datasource.url=jdbc:mariadb://localhost:3306/potatochip

spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

ollama.base-url=http://localhost:11434
ollama.model=llama3.2


spring.profiles.active=local


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

jwt.secret=your-very-long-secret-key-at-least-32-characters-long-1234567890
jwt.expiration=3600000

# kakao ?? ??? aip
kakao.client-id=db2d0db7403c7897ec33b069114230fd
kakao.client-secret=JYBAVQogmcjo2B8gJ4NpdnPu09f1oqOz
kakao.redirect-uri=http://localhost:8080/oauth2/callback/kakao

# naver ?? ??? aip
naver.client-id=dliSAvY7WLXBe3CoNRHo
naver.client-secret=XYt58KjhyV
naver.redirect-uri=http://localhost:8080/oauth2/callback/naver



#spring.ai.openai.api-key=dummy
#spring.autoconfigure.exclude=org.springframework.ai.model.openai.autoconfigure.OpenAiAudioSpeechAutoConfiguration


## AWS S3 ??
#cloud.aws.s3.bucket=potatochip-induk-prod-images
#
## AWS ?? (??)
#cloud.aws.region.static=ap-northeast-2
#
## ?? ? IAM Access Key ??
#cloud.aws.credentials.access-key=
#cloud.aws.credentials.secret-key=