spring.application.name=PotatoChip

#spring.datasource.url=jdbc:mariadb://localhost:3306/potatochip
spring.datasource.url=jdbc:mariadb://potatochip.cfkwqmeiiriy.ap-northeast-2.rds.amazonaws.com/potatochip
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

ollama.base-url=http://localhost:11434
ollama.model=llama3.2

spring.ai.anthropic.api-key=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
spring.ai.anthropic.chat.options.model=claude-opus-4-6

spring.profiles.active=local



spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB

jwt.secret=your-very-long-secret-key-at-least-32-characters-long-1234567890
jwt.expiration=3600000

# kakao ?? ??? aip
kakao.client-id=7f89f8b1152716f7a8cbf9f104e3b48d
kakao.client-secret=I1BBKvzjjBVlceHA75w2g9RIMTzKR6HW
kakao.redirect-uri=http://54.180.95.231:8080/oauth2/callback/kakao



# naver ?? ??? aip
naver.client-id=sH94826Wh2jz_3GceBpJ
naver.client-secret=yOxMoO8IjK
naver.redirect-uri=http://54.180.95.231:8080/oauth2/callback/naver


kakao.rest-api-key=513332d83f138e6325bf59831c7fb2f0

kakao.pay.admin-key=DEVF8A4DC51D5BE747DE16432177A5BEC108E4AB
kakao.pay.cid=TC0ONETIME
kakao.pay.ready-url=https://open-api.kakaopay.com/online/v1/payment/ready
kakao.pay.approve-url=https://open-api.kakaopay.com/online/v1/payment/approve
kakao.pay.approval-redirect=http://54.180.95.231:8080/api/pay/kakao/approve
kakao.pay.cancel-redirect=http://54.180.95.231:8080/orders
kakao.pay.fail-redirect=http://54.180.95.231:8080/orders
#spring.ai.openai.api-key=dummy
#spring.autoconfigure.exclude=org.springframework.ai.model.openai.autoconfigure.OpenAiAudioSpeechAutoConfiguration


## AWS S3 ??
#cloud.aws.s3.bucket=potatochip-induk-prod-images
#
## AWS ?? (??)
#cloud.aws.region.static=ap-northeast-2
#
## ?? ? IAM Access Key ??
#cloud.aws.credentials.access-key=
#cloud.aws.credentials.secret-key=