### AI 리뷰 총평 조회
GET http://localhost:8080/api/products/3/ai-review-summary


### AI 리뷰 총평 저장
POST http://localhost:8080/api/products/3/ai-review-summary/refresh


### AI 리뷰 총평 수정
PUT http://localhost:8080/api/products/3/ai-review-summary
Content-Type: application/json

{
  "summary": "PUT 방식으로 수정한 AI 리뷰 총평입니다.",
  "reviewCount": 10
}


### AI 리뷰 총평 비활성화
DELETE http://localhost:8080/api/products/3/ai-review-summary


### 비활성화 후 재저장 테스트
POST http://localhost:8080/api/products/3/ai-review-summary
Content-Type: application/json

{
  "summary": "DELETE 후 다시 POST로 새 내용처럼 저장한 AI 리뷰 총평입니다.",
  "reviewCount": 20
}

### productId 3 리뷰 작성 후 AI 총평 자동 갱신 테스트
POST http://localhost:8080/api/reviews
Content-Type: application/json

{
  "productId": 3,
  "userId": 1,
  "orderItemId": null,
  "rating": 5,
  "content": "감자가 모양은 조금 못생겼지만 맛은 정말정말 좋았습니다 예쁜 감자랑 맛은 똑같아요 가격도 저렴했습니다. 배송도 빨라서 만족했습니다.",
  "imageUrl": "",
  "repurchaseIntent": true
}


### productId 3 AI 리뷰 총평 조회
GET http://localhost:8080/api/products/3/ai-review-summary

### 존재하지 않는 AI 리뷰 총평 조회
GET http://localhost:8080/api/products/999/ai-review-summary

